from enum import StrEnum


class ErrorCode(StrEnum):
    """系统错误码枚举。

    用于统一错误响应格式的机器可读错误代码。
    """

    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"

    CONSENT_REQUIRED = "CONSENT_REQUIRED"
    HIGH_RISK_ALERT = "HIGH_RISK_ALERT"
    LAW_RETRIEVAL_FAILED = "LAW_RETRIEVAL_FAILED"

    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    PII_DETECTED = "PII_DETECTED"

    LLM_SERVICE_ERROR = "LLM_SERVICE_ERROR"
    LLM_TIMEOUT = "LLM_TIMEOUT"
