from enum import StrEnum


class ErrorCode(StrEnum):
    """Machine-readable error codes for the unified error response format."""

    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"

    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    CONSENT_REQUIRED = "CONSENT_REQUIRED"
    HIGH_RISK_ALERT = "HIGH_RISK_ALERT"
    LAW_RETRIEVAL_FAILED = "LAW_RETRIEVAL_FAILED"

    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    PII_DETECTED = "PII_DETECTED"
    SESSION_EXPIRED = "SESSION_EXPIRED"

    LLM_SERVICE_ERROR = "LLM_SERVICE_ERROR"
    LLM_TIMEOUT = "LLM_TIMEOUT"
